### ISSUE TITLE
Will asarmor affect app perfomance?

### ISSUE THREAD

**Issue by dyaskur** [sleeyax/asarmor#11]
It's seem sound amazing, but sorry I can't test yet, I'm just wondering will this affect app performance? I mean app resource usage(RAM/CPU/DISK) will higher when running app that use asarmor?  Or this just affect performance when develop/build only?

Thanks in advance

**Comment by sleeyax** [comment]
No, it won't affect performance. Electron will load your asar just fine after protections were applied using asarmor.
