### ISSUE TITLE
[suggestion] maybe should add a tip...

### ISSUE THREAD

**Issue by Moon1102** [sleeyax/asarmor#16]
if someone use asarmor + leveldb + electron-builder and NOT add `asarmor` to  ```electronBuilder:{externals:[]}```, running the packaged program will report an error  about `leveldb LOCK xxx`

Config file like this is work for me:
```
 electronBuilder: {
      externals: ["level", "asarmor"],
}
```

**Comment by Moon1102** [comment]
Emmm but after add asarmor to  `electronBuilder.externals`, app.asar can extract by `asar -e`.

Is there a conflict between `asarmor` and `level`? 😭

**Comment by sleeyax** [comment]
Thank you for the suggestion. 

Make sure asarmor is actually applied, it shouldn't 'conflict' with another package unless it's doing a similar thing (i.e modifying your asar file) maybe.

**Comment by Moon1102** [comment]
请联系我的 QQ726451484

**Comment by sleeyax** [comment]
I'm not chinese and don't use QQ. I'd rather resolve this through GitHub. Is it possible to create a small, reproducible example? You can create a separate public GitHub repo for me to check.

**Comment by sleeyax** [comment]
Btw I can't find `externals`mentioned in the electron builder docs. It looks like it's a webpack config option though https://webpack.js.org/configuration/externals/

**Comment by Moon1102** [comment]
You're right. It shouldn't 'conflict' with another package. Maybe I didn't make a further judgment  and  think the LOCK error caused by change of ASAR file (as the figure shown) 😭😭
<img width="547" alt="图片" src="https://user-images.githubusercontent.com/15380331/146865038-207f74b5-d5b0-4509-8bcc-fd2f5323a555.png">

Today, when I make the minimize project and review the code again, the error disappeared and I could pack it normally. Although I haven't really located it yet,but it is obvious that it is not caused by the conflict between `asarmor` and `level`

It brings you extra work，I should apologize for that.

**Comment by sleeyax** [comment]
Hey no worries! If you have further issues please reopen this issue.
