### ISSUE TITLE
File size limit

### ISSUE THREAD

**Issue by christopherGr** [sleeyax/asarmor#4]
Hello,

I am writing to ask you why there is size limit of 2gb?
I try to asarmor a 4gb .asar file and i can't.
Is there any possibility to expand the size limit?

**Comment by sleeyax** [comment]
>  I try to asarmor a 4gb .asar file and i can't.
Why can't you? Asarmor doesn't explicitly set any file size limits. Please elaborate; do you get an error or something? "and i can't" doesn't tell me anything.

**Comment by christopherGr** [comment]
In smaller .asar files everything is fine... but when i type in command line 
npx asarmor -a app.asar -o asarmor.asar --trashify bee-movie.txt foo.js bar.ts
it does not create a new asarmor.asar file and command line outputs the following message: 
File size(4470914419) is greater than 2 GB

Thank you for your reply...
