### ISSUE TITLE
Encryption: load plaintext asar

### ISSUE THREAD

**Issue by sleeyax** [sleeyax/asarmor#41]
We should be able to load/hook an unencrypted asar so we can import and use the modules it contains in our project.

Some work has been done on this already but isn't complete nor tested yet, see `hooks/node-modules.ts`.

**Comment by burgil** [comment]
I would like to suggest a way to bullet-proof your own code by simply adding a decrypt option that requires said key.txt to decrypt it, maybe proving on the process that it can only be decrypted using that key, currently I saw we can only backup and restore but you also commented somewhere that it will defeat the purpose of asarmor to add decryption, but I say, only if it does not requires the key to disable the protections, if it does, it's safe. idk how it really works lol but hope I helped good luck :)

**Comment by sleeyax** [comment]
@burgil I appreciate your enthusiasm but your comment is off topic regarding this issue. Please open another discussion and bundle any more questions you might have.
