### ISSUE TITLE
gyp Error when trying to install latest beta (2.1.0-beta.9) as a library on Windows

### ISSUE THREAD

**Issue by DemBackfisch** [sleeyax/asarmor#53]
Hey, i was trying to install the latest beta version (2.1.0-beta.9) of asarmor as a library, but got this error: `gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp`, installing latest stable version (2.0.0) works fine.

**Comment by sleeyax** [comment]
Thank you for opening an issue. Can you please provide more information such as:
- your operating system (windows, mac,  linux, ...)
- package manager used to install the package (npm, yarn, ...)
- Node.js version (run node -v in a terminal)

**Comment by DemBackfisch** [comment]
OS: windows
package manager: npm 8.18.0
Node version v16.10.0

I also researched this issue and found out that you can fix it by adding `"openssl_fips": ""` in variables inside the binding.gyp
Now obviously i can´t change the file inside the actual package, but I tested this by adding the variable as an argument during the installation like this: `npm install --openssl_fips='' asarmor` and it worked.

**Comment by sleeyax** [comment]
`npm install asarmor@2.1.0-beta.10` should work now.
