### ISSUE TITLE
Node Integration true shoudn't be a security issue?

### ISSUE THREAD

**Issue by TrofinSorin** [sleeyax/asarmor#54]
Great tool btw ! I have a security related question.

I'm worried about `nodeIntegration: true` option as i've read [this article](https://stackoverflow.com/questions/57505082/would-it-be-safe-to-enable-nodeintegration-in-electron-on-a-local-page-that-is-p/57507392#57507392).

If we build it with asarmor it shoudn't be an issue right? Because it's encrypted.

```
const mainWindow = new BrowserWindow({
    // ...
    webPreferences: {
      nodeIntegration: true,   // MUST BE ENABLED
      contextIsolation: false, // MUST BE DISABLED
    },
});
```

Thank you !

**Comment by sleeyax** [comment]
Unfortunately, if you want to utilize asarmor's encryption module, `nodeIntegration` has to be set to `true` so the asar can be decrypted at runtime. 

Enabling `nodeIntegration` only imposes risks at runtime. Whether the asar is encrypted with asarmor is irrelevant. As your the StackOverflow reply you linked states:

> Enabling nodeIntegration only imposes risks if you load and execute code from untrusted sources, i.e. the internet or from user input.

So if your app itself is secure and either doesn't accept user input or sanitizes it correctly, you have nothing to worry about.

**Comment by TrofinSorin** [comment]
What about the encryption key? If it's stored in the project, it could be used to decrypt it?
I'm pretty new to this so i'm just curious.

**Comment by sleeyax** [comment]
The encryption key is randomly generated at build time (see scripts/keygen.js) and stored in your `node_modules/asarmor/.../key.txt` for reuse. So it's basically unique per project.

________________________________

**Comment by TrofinSorin** [comment]
So basically users can't access the key to unpack the app.asar right?

**Comment by sleeyax** [comment]
Users and noobs can't easily find the key to decrypt, reverse engineers who know what they are doing probably can. As mentioned in this projects readme, asarmor is not bulletproof. Do your own research and evaluate whether asarmor meets your security expectations.

**Comment by TrofinSorin** [comment]
Thank you for info and thank you for this package. Closing this
