### ISSUE TITLE
Does not protect against a simple 7zip extract

### ISSUE THREAD

**Issue by laztheripper** [sleeyax/asarmor#59]
With 7zip and the asar format plugin from tc4shell, the archive can be extracted easier than with the cli.

**Comment by sleeyax** [comment]
The base protection (trashify) broke and has been removed in https://github.com/sleeyax/asarmor/releases/tag/v3.0.0. I suggest you update asarmor and use encryption instead.

**Comment by ape-casear** [comment]
> The base protection (trashify) broke and has been removed in https://github.com/sleeyax/asarmor/releases/tag/v3.0.0. I suggest you update asarmor and use encryption instead.

I have a question. Can a malicious person use Ghidra to open main.node and then decompile to get the aeskey?

**Comment by sleeyax** [comment]
A malicious person can do anything. Asarmor, as stated in the readme, is not bulletproof. Nothing is.
