### ISSUE TITLE
Application entry file does not exist?

### ISSUE THREAD

**Issue by Naozumi520** [sleeyax/asarmor#60]
This is the first time I use the library method to encrypt the app, but I'm getting issue, here is my afterPack.js and my app directory:
<img width="1375" alt="Screenshot 2023-01-23 at 12 09 38 AM" src="https://user-images.githubusercontent.com/52615455/213926283-c70bdadc-4b11-44e6-8c0e-f22ef37be0dc.png">

When I run the pack command, it show the Application entry file does not exist error, did I did something wrong with it?

<img width="1792" alt="Screenshot 2023-01-23 at 12 13 28 AM" src="https://user-images.githubusercontent.com/52615455/213926448-898c8303-e0c0-410f-bb8e-2746497f9168.png">

I tried to use the asar unpack command and index.js is actually there, and it's contents are encrypted.

**Comment by sleeyax** [comment]
Please try the latest release https://github.com/sleeyax/asarmor/releases/tag/v3.0.0. You may reopen this issue if it doesn't solve your issue.
