### ISSUE TITLE
main.node is not a win32 application

### ISSUE THREAD

**Issue by chrisgordon** [sleeyax/asarmor#65]
I'm able to package and run my Electron app on macOS, however not on Windows. I get:
![image](https://github.com/sleeyax/asarmor/assets/1111043/5d7f256f-c4d3-4955-8f25-d29da8ebd181)

I've done a rebuild with `npm rebuild` which appeared to run successfully and recreated main.node and renderer.node.  Didn't fix it.

Please help.

**Comment by chrisgordon** [comment]
Actually I'm wondering - was it originally built as a 64-bit module?  
I'm packaging using a 32-bit Electron, so maybe that's the issue?

**Comment by sleeyax** [comment]
@chrisgordon so what was your solution? Other people may experience the same issue in the future so share your findings please!
