### ISSUE TITLE
Understanding trashify behavior

### ISSUE THREAD

**Issue by srcastor** [sleeyax/asarmor#70]
Hello there, first off thanks you so much for this library  🤘

I have successfully completed all the steps to patch my asar file, however, I struggle to understand the purpose of the trashify  patch
I tried multiple approachs from this template, including adding a filename array of 500 random names
```
  archive.patch(asarmor.createTrashPatch({
    filenames: ['foo', 'bar'],
    beforeWrite: (filename) => {
      const extensions = ['js', 'ts', 'tsx', 'txt'];
      const extension = extensions[Math.floor(Math.random() * extensions.length)];
      return filename + '.' + extension;
    }
  }));
```
I test how this affects to the extraction with the command `npx @electron/asar extract ./resources/app.asar /out`

I always get multiple console errors as a result, but anyway the extraction is done completely and I see absolutely all files. I guess I'm missing something

```
RangeError [ERR_INVALID_ARG_VALUE]: The argument 'size' is invalid. Received 3.6070516137455966e+307
RangeError [ERR_INVALID_ARG_VALUE]: The argument 'size' is invalid. Received 2.1199720750809106e+307
RangeError [ERR_INVALID_ARG_VALUE]: The argument 'size' is invalid. Received 7.202901386823941e+307
    at Function.alloc (node:buffer:366:3)
    at Object.module.exports.readFileSync (node_modules\@electron\asar\lib\disk.js:106:23)
    at Object.module.exports.extractAll (node_modules\@electron\asar\lib\asar.js:206:30).......
```

Regards

**Comment by sleeyax** [comment]
It's possible that the asar CLI has been updated. This protection used to work by adding an invalid entry with an impossible size, causing the CLI to fail and quit with that `RangeError` you're seeing. But from your logs it looks like it's throwing a warning and continuing instead. As a result it skips over bad files and continues to read valid entries. Basically defeats the purpose of the protection. Keep in mind that asarmor hasn't seen a real update in 2 years. I plan to overhaul it sometime but didn't get to it yet. I'll probably focus more on encryption going forward.

**Comment by srcastor** [comment]
yeah, that sounds very reasonable 
I agree the way to go is encryption, in any case thank you very much for your effort and dedication.

**Comment by sleeyax** [comment]
The trashify patch has been removed in https://github.com/sleeyax/asarmor/releases/tag/v3.0.0 because it simply no longer works. Encryption has been improved in this release so I suggest you upgrade and check it out.
