### ISSUE TITLE
Errors in main.js when attempting to use encryption

### ISSUE THREAD

**Issue by jritch** [sleeyax/asarmor#77]
Hi, thank you for this repo!

I've been following the new instructions in the Readme to get encryption working on my `electron-react-boilerplate`-based app, and I think I've followed them correctly - `./src/main/main.node` is my entry point in my app's root `package.json` file and my asar has encrypted files in it. 

![image](https://github.com/sleeyax/asarmor/assets/2490406/eb62d86d-2885-4d11-aafd-b07f562a0345)

However, when I try to run the electron app after installation I get this error message, and it looks like it is trying to load the encrypted main.js

![image](https://github.com/sleeyax/asarmor/assets/2490406/060c683e-d3ac-4f37-bcdc-b2cf4c052201)

**I noticed that `release/app/package.json` still had `main.js` as the "main" target - modifying that file to also point to `main.node`, I now get a different error message, so I think that at least let me load `main.js` correctly?** - **Maybe this should be added as instruction in the readme.**

![Screenshot 2024-05-01 183339](https://github.com/sleeyax/asarmor/assets/2490406/14507dcd-1d5c-4f00-9deb-f44aadf14d3e)

This error message seemed to be resolved by changing 

`module.exports = function bootstrap(k: Uint8Array) {...`

to `export default function bootstrap(k: Uint8Array) {...`

But now I get a new error 

![image](https://github.com/sleeyax/asarmor/assets/2490406/5cfc4bb6-624b-4518-8ae5-9f5de997bdf1)

Any idea what might be going wrong at this stage?

**Comment by jritch** [comment]
Might be related to a difference in electron versions? I'm on `"^25.0.1"`

https://stackoverflow.com/questions/75668307/error-in-native-callback-using-ffi-napi-in-electron-and-electron-builder/75978712#75978712

**Comment by sleeyax** [comment]
Hi @jritch did you manage to resolve this issue? I'm not sure what that last error is supposed to mean either. But the fact your `package.json` didn't change properly at build time also worries me.
