### ISSUE TITLE
How to use in Electron Forge

### ISSUE THREAD

**Issue by nijinekoyo** [sleeyax/asarmor#78]
I read README.md, but I still don't understand how to use this library in Electron Forge

**Comment by nijinekoyo** [comment]
Sorry, I don't really understand most of it, for example, where should `afterPack.js` be registered
So I want to ask if there is a similar example project that I can refer to?
Thank you very much for your help

**Comment by sleeyax** [comment]
>  So I want to ask if there is a similar example project that I can refer to?

https://github.com/sleeyax/asarmor/tree/master/example/electron

**Comment by sleeyax** [comment]
Wait, I was confused. Asarmor only officially supports `electron-builder` at the moment. But if `electron-forge` has an equivalent to `electron-builder`'s `afterPack` script, then you might be able to make it work.

**Comment by nijinekoyo** [comment]
Yesterday I tried to add code according to the example of `electron-builder`
I tried it in the following two hooks
https://www.electronforge.io/config/hooks#postpackage
https://electron.github.io/packager/main/interfaces/Options.html#afterAsar

But I encountered an error. When the asar file is modified in these hooks, an error will appear. Electron forge seems to continue to read and verify the contents of the asar file in the final make stage. I don't know how to solve this problem

**Comment by sleeyax** [comment]
Looks like it should be possible using `postPackage` and `packageAfterCopy`. I'm experimenting with and am getting very close, only the render process description seems stuck for some reason when you launch the app. Hopefully I can figure it out and update the README.md.

**Comment by sleeyax** [comment]
If you want to help look into it, check out https://github.com/sleeyax/electron-forge-asarmot-test/commit/52b692cbf4631a5d97dc95f1c0cb8c64f5367865

**Comment by sleeyax** [comment]
Figured it out, will update the project README soon.

**Comment by nijinekoyo** [comment]
Because the project I was working on when I asked the question had already been released, I didn't study it later, but I still look forward to your results.
